SET encoding UTF8
SET SQLFORMAT DELIMITED |

SELECT 
    PATIENT.PAT_ID,
    PATIENT.PAT_NAME,
    PATIENT.PAT_BIRTHDATE,
    PATIENT.PAT_SEX,
    STUDY.STUDY_IUID,
    STUDY.STUDY_ID,
    STUDY.STUDY_DATETIME,
    STUDY.STUDY_DESC,
    STUDY.MODS_IN_STUDY,
    STUDY.CUIDS_IN_STUDY,
    STUDY.NUM_SERIES,
    STUDY.NUM_INSTANCES,
    STUDY.CREATED_TIME,
    STUDY.UPDATED_TIME,
    SERIES.SERIES_IUID,
    SERIES.SERIES_NO,
    SERIES.MODALITY,
    SERIES.BODY_PART,
    SERIES.SERIES_DESC,
    SERIES.INSTITUTION,
    SERIES.STATION_NAME,
    SERIES.PERF_PHYSICIAN,
    SERIES.PPS_START,
    SERIES.PPS_IUID,
    SERIES.NUM_INSTANCES,
    INSTANCE.SOP_IUID,
    INSTANCE.SOP_CUID,
    INSTANCE.INST_NO,
    INSTANCE.CONTENT_DATETIME,
    INSTANCE.CREATED_TIME,
    INSTANCE.UPDATED_TIME,
    INSTANCE.INST_SIZE,
    FILES.FILEPATH,
    FILES.FILE_TSUID,
    FILES.FILE_MD5,
    FILES.FILE_SIZE,
    FILES.CREATED_TIME
FROM 
    PATIENT
JOIN 
    STUDY ON PATIENT.PK = STUDY.PATIENT_FK
JOIN 
    SERIES ON STUDY.PK = SERIES.STUDY_FK
JOIN 
    INSTANCE ON SERIES.PK = INSTANCE.SERIES_FK
JOIN 
    FILES ON INSTANCE.PK = FILES.INSTANCE_FK
;
